<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="0" failed="3" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[test case has been failed]]>
    </line>
    <line>
      <![CDATA[test case has been failed]]>
    </line>
    <line>
      <![CDATA[test case has been failed]]>
    </line>
  </reporter-output>
  <suite started-at="2024-10-10T09:07:31 IST" name="Default suite" finished-at="2024-10-10T09:08:45 IST" duration-ms="73836">
    <groups>
    </groups>
    <test started-at="2024-10-10T09:07:31 IST" name="Default test" finished-at="2024-10-10T09:08:45 IST" duration-ms="73836">
      <class name="Pkg_maven.Amz_project.Products_sort_price">
        <test-method is-config="true" signature="Amz_login()[pri:0, instance:Pkg_maven.Amz_project.Products_sort_price@2a265ea9]" started-at="2024-10-10T09:07:31 IST" name="Amz_login" finished-at="2024-10-10T09:07:45 IST" duration-ms="13997" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Amz_login -->
        <test-method signature="price_hightolow()[pri:0, instance:Pkg_maven.Amz_project.Products_sort_price@2a265ea9]" started-at="2024-10-10T09:07:45 IST" name="price_hightolow" finished-at="2024-10-10T09:08:02 IST" duration-ms="16232" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[the products in search page are not shown in descending order of price expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: the products in search page are not shown in descending order of price expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at Pkg_maven.Amz_project.Amz_search_page.verify_searchresult_hightolow(Amz_search_page.java:103)
at Pkg_maven.Amz_project.Products_sort_price.price_hightolow(Products_sort_price.java:28)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[test case has been failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- price_hightolow -->
        <test-method is-config="true" signature="Amz_logout()[pri:0, instance:Pkg_maven.Amz_project.Products_sort_price@2a265ea9]" started-at="2024-10-10T09:08:02 IST" name="Amz_logout" finished-at="2024-10-10T09:08:10 IST" duration-ms="8584" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Amz_logout -->
        <test-method is-config="true" signature="Amz_login()[pri:0, instance:Pkg_maven.Amz_project.Products_sort_price@2a265ea9]" started-at="2024-10-10T09:08:10 IST" name="Amz_login" finished-at="2024-10-10T09:08:15 IST" duration-ms="5048" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Amz_login -->
        <test-method signature="price_lowtohigh()[pri:0, instance:Pkg_maven.Amz_project.Products_sort_price@2a265ea9]" started-at="2024-10-10T09:08:15 IST" name="price_lowtohigh" finished-at="2024-10-10T09:08:25 IST" duration-ms="10005" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[the products in search page are not shown in ascending order of price expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: the products in search page are not shown in ascending order of price expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at Pkg_maven.Amz_project.Amz_search_page.verify_searchresult_lowtohigh(Amz_search_page.java:90)
at Pkg_maven.Amz_project.Products_sort_price.price_lowtohigh(Products_sort_price.java:18)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[test case has been failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- price_lowtohigh -->
        <test-method is-config="true" signature="Amz_logout()[pri:0, instance:Pkg_maven.Amz_project.Products_sort_price@2a265ea9]" started-at="2024-10-10T09:08:25 IST" name="Amz_logout" finished-at="2024-10-10T09:08:27 IST" duration-ms="2183" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Amz_logout -->
        <test-method is-config="true" signature="Amz_login()[pri:0, instance:Pkg_maven.Amz_project.Products_sort_price@2a265ea9]" started-at="2024-10-10T09:08:27 IST" name="Amz_login" finished-at="2024-10-10T09:08:33 IST" duration-ms="5350" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Amz_login -->
        <test-method signature="sort_reviews()[pri:0, instance:Pkg_maven.Amz_project.Products_sort_price@2a265ea9]" started-at="2024-10-10T09:08:33 IST" name="sort_reviews" finished-at="2024-10-10T09:08:43 IST" duration-ms="10509" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[the products in search page are not shown in ascending order of average customer reviews expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: the products in search page are not shown in ascending order of average customer reviews expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at Pkg_maven.Amz_project.Amz_search_page.verify_searchresult_reviewsort(Amz_search_page.java:117)
at Pkg_maven.Amz_project.Products_sort_price.sort_reviews(Products_sort_price.java:39)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[test case has been failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- sort_reviews -->
        <test-method is-config="true" signature="Amz_logout()[pri:0, instance:Pkg_maven.Amz_project.Products_sort_price@2a265ea9]" started-at="2024-10-10T09:08:43 IST" name="Amz_logout" finished-at="2024-10-10T09:08:45 IST" duration-ms="1859" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Amz_logout -->
      </class> <!-- Pkg_maven.Amz_project.Products_sort_price -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
